---
deployment:
  tasks:
    # Paths
    - export REPO=/home/haroot/repositories/DisptchPro
    - export BACKEND=$REPO/backend
    - export PHP=/usr/local/bin/php
    - export COMPOSER=/opt/cpanel/composer/bin/composer

    # Backend dependencies
    - cd $BACKEND && $COMPOSER install --no-dev --optimize-autoloader

    # Laravel maintenance & migrations (remove migrate if you prefer manual)
    - cd $BACKEND && $PHP artisan down || true
    - cd $BACKEND && $PHP artisan migrate --force

    # Optimize caches
    - cd $BACKEND && $PHP artisan config:cache
    - cd $BACKEND && $PHP artisan route:cache
    - cd $BACKEND && $PHP artisan view:cache
    - cd $BACKEND && $PHP artisan optimize

    # Ensure storage symlink exists
    - if [ ! -e "$BACKEND/public/storage" ]; then cd $BACKEND && $PHP artisan storage:link; fi

    # Bring app back up
    - cd $BACKEND && $PHP artisan up
